### ISSUE TITLE
weird timestamps

### ISSUE THREAD

**Issue by ffraaz** [NeoLSN/cordova-plugin-gyroscope#2]
Hi,
do you know why the timestamps are not in the same date format as the timestamps in the acceleration, orientation and geolocation plugins?
![example](https://cloud.githubusercontent.com/assets/12122389/14916848/37cfa438-0e1c-11e6-8b14-652b9245d898.jpg)

**Comment by NeoLSN** [comment]
Which platform of device are you using? iOS / Android?

**Comment by NeoLSN** [comment]
@ffraaz 
I think where the issue is. I directly used `event.timestamp` without processing it, so the time is very different than other library. Right now, I changed to use `System.currentTimeMillis()` as the timestamp value.

Can you please try again and tell me it is fixed or not? Hope it will fit your expectation.

**Comment by ffraaz** [comment]
I'm using Android.
It's working for me now.
Thanks a lot!
